### PR TITLE
Collapse multiple bar style tags

### PR DESCRIPTION
**Pull request by semanticart**
Before this patch, we render 1 style tag per player (+1 for franchise
ratings). This collapses all those down into a single style tag which
makes the page a little smaller and makes the browser do a little less
work.

before

after

@adarowski mind taking a look before giving this a merge? I don't think it breaks anything but I would love some confirmation.

If you [add `w=1` to the url](https://github.com/adarowski/Hall-of-Stats/pull/5/files?w=1) then it should make the comparison easier to parse visually.

### CODE REVIEW

**Comment by adarowski** [comment]
This looks good and makes sense to me. I added a commit that I believe removes even more extraneous lines. I don't see any issues after removing them, but wanted to make sure just in case of caching.

Also, for the `$max_hall_rating` is there a way to just dynamically pull in Babe Ruth's Hall Rating in case it changes? If not, no biggie. Thanks!

**Comment by semanticart** [comment]
I pushed another commit that does 2 big things:

1. Stop using the slow sass filter in Haml
2. Make the max hall rating dynamic.

This will make things faster and more future-proof.

Let me know if anything looks askew but it should match the output of your commit 100%. It won't match the .com version 100% because we're using a more precise number from Babe Ruth's hall rating now so the percentages change very slightly.

**Comment by semanticart** [comment]
Current output:
screen shot 2016-08-12 at 8 36 24 am

**Comment by semanticart** [comment]
> This looks good and makes sense to me. I added a commit that I believe removes even more extraneous lines. I don't see any issues after removing them, but wanted to make sure just in case of caching.

This looks good afaict. It shouldn't matter to caching since the cache is busted on every deploy.

**Comment by adarowski** [comment]
Getting this error on the player page… does this happen because the sass filter is still used in this case?

screen shot 2016-08-12 at 9 21 44 am

**Comment by adarowski** [comment]
Otherwise, the player lists are looking 💯

**Comment by semanticart** [comment]
@adarowski should be good now. Let me know if you see anything askew.

**Comment by adarowski** [comment]
🏆  Thanks!

**Pull request merged**
